theme: jekyll-theme-cayman
title: Cannatology
description: >
  I ramble.

  This is a blog about cannabis, photography, martial arts, 
  and sometimes software.
github_username: cannatology
markdown: kramdown
kramdown:
  parse_block_html: true
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
  - html-proffer
baseurl: "/"
url: "https://cannatology.gitub.io"
github: [metadata]
